name: flutter_application_nilesh
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.3
  http: ^0.13.6
  cached_network_image: ^3.3.1
  google_fonts: ^4.0.4
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  logger: ^2.3.0
  flutter_secure_storage: ^8.1.0
  path: ^1.8.3
  sqflite: ^2.3.2
  fluttertoast: ^8.2.5
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  retrofit_generator: '>=7.0.0 <8.0.0'   
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter: 
  uses-material-design: true

